### ISSUE TITLE
Unable to Edit Sitegroups in DNN 9.4 + Permission asked to add this to the DNN CE Platform

### ISSUE THREAD

**Issue by thabaum** [SCullman/Connect.Sitegroups#2]
https://github.com/dnnsoftware/Dnn.Platform/issues/2745

According to this DNN issue @valadas was wondering if you would be willing to add this to the AdminExperience and also if there is a way you can test it working against 9.4 version.

I would love to see this feature fully supported in DNN CE, thank you!

**Comment by SCullman** [comment]
This was my pet project to learn both react and Persona Bar.

- It is currently not working, as it misses the required [upgrade steps for  DNN9.3](https://www.dnnsoftware.com/community-blog/cid/156674/upgrading-persona-bar-components-for-dnn-93). 
- I would be happy to hand this code over to AdminExperience.

**Comment by thabaum** [comment]
Thank you Stefan.  It would be a great addition to help manage portals I hope it can be added soon.  I will try to keep this ball rolling.  Thanks again, big time!

**Comment by thabaum** [comment]
Is there anyway by chance you can add this as a pull request with the upgrade steps applied?  Then the rest of DNN CE team can start fixing any bugs or add features if needed for future releases.

**Comment by SCullman** [comment]
@thabaum, maybe my statement was not clear enough.  

 I wrote this module just to learn both React and Persona Bar. I also learned that I don't like to code in Javascript directly, and I found my own way to [write modules for DNN](https://fable.io).  

_Site groups_ are technically boring and simple. On the server side, the API has existed for a long time and only needs to be published with WebAPI. Years ago I showed at the DNN Europe how to connect it with Knockout on the front side. 

I don't need _site groups_ in any of my business projects. I am not getting paid for that, I learn nothing new, and I have enough site projects and ideas to fill up my spare time totally. And for sure: I certainly will never ever commit myself for tasks just because somebody asks me for that.  

This project has a MIT license, and it is published here on github. If anyone likes this code, she is free to fork and to do what ever she wants. She  even don't have to ask me, and this is fine!   

So please do me a big favor and don't put me under pressure. I'm happy to help, and maybe I'll be able to renew the code and get it running again sometime in the days to come.

But don't rely on it., this was not a commitment for fast action.
